# Generated by Django 3.1.7 on 2021-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_book_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='gener',
        ),
        migrations.AddField(
            model_name='book',
            name='gener',
            field=models.ManyToManyField(to='accounts.Gener'),
        ),
    ]
